controller_list:
  - name: arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - ur10shoulder_pan_joint
      - ur10shoulder_lift_joint
      - ur10elbow_joint
      - ur10wrist_1_joint
      - ur10wrist_2_joint
      - ur10wrist_3_joint